server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  config:
    import: classpath:db-config.properties
  datasource:
    hikari:
      database1:
        pool-name: hikari-default
        jdbc-url: ${database1.url}
        username: ${database1.username}
        password: ${database1.password}
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        connection-test-query: SELECT 'database1'
        mapper-locations: classpath:mapper/**/*.xml
      database2:
        pool-name: hikari-second
        jdbc-url: ${database2.url}
        username: ${database2.username}
        password: ${database2.password}
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        connection-test-query: SELECT 'database2'
        mapper-locations: classpath:mapper/database2/*.xml

## mybatis config
mybatis:
  type-aliases-package: com.koda.multitranx
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    call-setters-on-nulls: true
